In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
# 3ノード　→　2ノードの全結合層(fully-connected layer)
fc = nn.Linear(3, 2)

In [4]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [5]:
fc.weight

Parameter containing:
tensor([[ 0.4195,  0.4377, -0.1818],
        [-0.0819, -0.3917, -0.4783]], requires_grad=True)

In [6]:
fc.bias

Parameter containing:
tensor([-0.1875, -0.4761], requires_grad=True)

In [8]:
# 乱数のシードを固定
torch.manual_seed(0)

In [9]:
fc = nn.Linear(3, 2)

In [10]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [11]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)